name: "Amazon Linux: Build and push toolbx images"

permissions: read-all

on:
  pull_request:
    branches:
      - main
    paths:
      - amazonlinux/**
      - .github/workflows/amazonlinux.yaml
      - .github/workflows/build-push-images.yaml
  push:
    branches:
      - main
    paths:
      - amazonlinux/**
      - .github/workflows/amazonlinux.yaml
      - .github/workflows/build-push-images.yaml
  schedule:
    - cron:  '0 0 * * MON'

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentially for the main branch. Also cancel in progress workflow runs for
# pull requests only.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-push-images:
    uses: ./.github/workflows/build-push-images.yaml
    with:
      distro: amazonlinux
      releases: 2 2023
      latest-release: 2023
      registry: quay.io/toolbx-images
      platforms: linux/amd64, linux/arm64
    secrets:
      registry-user: ${{ secrets.BOT_USERNAME }}
      registry-password: ${{ secrets.BOT_PASSWORD }}
      cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
