name: "Rocky Linux: Build and push toolbx images"

permissions: read-all

on:
  push:
    branches:
      - main
    paths:
      - rockylinux/**
      - .github/workflows/rockylinux.yaml
  schedule:
    - cron:  '0 0 * * MON'

# Prevent multiple workflow runs from racing
concurrency: ${{ github.workflow }}

env:
  distro: 'rockylinux'
  distro_pretty: 'Rocky Linux'
  latest_release: '9'

jobs:
  build-and-push-images:
    strategy:
      matrix:
        release: ['8', '9']

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: 'toolbx-images+github'
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Build and push ${{ env.distro_pretty }} ${{ matrix.release }} toolbox image
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.distro }}/${{ matrix.release }}
          file: ${{ env.distro }}/${{ matrix.release }}/Containerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: quay.io/toolbx-images/${{ env.distro }}-toolbox:${{ matrix.release }}

      - name: Push latest tag
        if: env.latest_release == matrix.release
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.distro }}/${{ matrix.release }}
          file: ${{ env.distro }}/${{ matrix.release }}/Containerfile
          platforms: linux/amd64,linux/arm64
          push: true
          no-cache: true
          tags: quay.io/toolbx-images/${{ env.distro }}-toolbox:latest
